### ISSUE TITLE
XHTML compliant code generated by the extension

### ISSUE THREAD

**Issue by ezze** [sensorario/lyiightbox#17]
I want to propose some improvements to make a code generated by your extension XHTML compliant. I don't know whether everything I propose is possible with lightbox2 but I will be very thankful if you will try to implement it.

My issue is based on response of [w3.org's validator](http://validator.w3.org/). A single photo's link element generated by your extension looks like this:

```
<a href="/images/photos/childhood-01.jpg" rel="lightbox[_Gallery]" title="Childhood"><img src="/images/photos/childhood-01-mini.jpg" border="0" /></a>
```

Validator says:

```
character "[" is not allowed in the value of attribute "rel"
```

probably, it would be possible to introduce some separator character (e.g "-") between "lightbox" and a name of a gallery;

```
there is no attribute "border"
```

one can customize image's look using CSS;

```
required attribute "alt" not specified
```

picture's description could be used here.

Of course, XHTML compliant code can be an optional parameter of the widget.

**Comment by sensorario** [comment]
I think this is a Lightbox2 stuff.

**Comment by ezze** [comment]
I've just tested it by myself. And yes, you are right. Lightbox2 alters a valid XHTML code even if I didn't specify a group, omitted a border or added an alternative text. It's a bit of disappointment. But somehow, a single image example's code on [Lightbox2 page](http://lokeshdhakar.com/projects/lightbox2/) is a valid XHTML.

I'm sorry that I disturbed you. I think you can close the issue if there is no way to solve it.

**Comment by sensorario** [comment]
Ok, Ill'close this issue.
